security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        oauth_token:
            pattern: ^/oauth/v2/token
            security: false
        #api_doc:
        #    pattern: ^/api/doc
        #    security: false
        api:
            pattern: ^/(users|tags|categories|products)\/(create|delete|update).*$
            fos_oauth: true
            stateless: true
            anonymous: false
        api_homepage:
            pattern: ^/
            security: false

